---
title: "Make Combination Kinome Inhibition States for Combos tested in Validation Data"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tictoc)

knitr::opts_knit$set(root.dir = here())
```

```{r}
validation_klaeger_drug_matches = read_csv(here('results/matching/validation_klaeger_matches.csv'))

all_validation_data = read_csv(here('results/ALMANAC_klaeger_models/breast_cancer_models/validation/all_validation_data.csv'))

klaeger = read_rds(here('results/klaeger_full_tidy.rds'))
```

```{r}
all_validation_data_filtered = all_validation_data %>% 
  filter(drug1 %in% validation_klaeger_drug_matches$validation_name &
           drug2 %in% validation_klaeger_drug_matches$validation_name)

all_combos_in_validation = all_validation_data_filtered %>% 
  select(drug1, drug2) %>% 
  unique() %>% 
  left_join(validation_klaeger_drug_matches, by = c('drug2' = 'validation_name')) %>% 
  select(-drug2, -cid) %>% 
  rename(drug2 = klaeger_name)

klaeger_wide_matched = read_rds(here('results/klaeger_full_tidy.rds')) %>%
	mutate(act_gene_name = paste0("act_",gene_name)) %>%
	select(-gene_name) %>% 
	filter(drug %in% validation_klaeger_drug_matches$klaeger_name) %>% 
	pivot_wider(names_from = act_gene_name, values_from = relative_intensity)

input_drug_1 = "Lapatinib"
input_drug_2 = "Afatinib"
input_conc_1 = klaeger_wide_matched$concentration_M[2]
input_conc_2 = klaeger_wide_matched$concentration_M[3]

test = klaeger_wide_matched %>% 
			filter(drug == input_drug_1, concentration_M == input_conc_1)

test = klaeger_wide_matched %>% 
			filter(drug == input_drug_2, concentration_M == input_conc_2)

calc_klaeger_combo_truncated <- function(input_drug_1, input_drug_2, input_conc_1, input_conc_2) {
	
	klaeger_combo = bind_rows(
		klaeger_wide_matched %>% 
			filter(drug == input_drug_1, concentration_M == input_conc_1),
		klaeger_wide_matched %>% 
			filter(drug == input_drug_2, concentration_M == input_conc_2)
	) %>% 
		pivot_longer(starts_with('act_'), names_to = 'kinase', values_to = 'value') %>% 
		select(-concentration_M) %>%
		pivot_wider(names_from = drug, values_from = value) %>% 
		rename('X1' = input_drug_1, 'X2' = input_drug_2) %>% 
		mutate(lowest_value = if_else(
			X1 > X2,
			X2,
			X1
		),
		combo_value = if_else(
			X1 >= 1 & X2 >= 1, 
			lowest_value,
			X1*X2
		)) %>% 
		select(-lowest_value, -X1, -X2) %>% 
		pivot_wider(names_from = kinase, values_from = combo_value)
	
	return(klaeger_combo)
}

possible_klaeger_combos = crossing(
  all_combos_in_validation,
	concentration_M_d1 = unique(klaeger_wide_matched$concentration_M),
	concentration_M_d2 = unique(klaeger_wide_matched$concentration_M)
) %>% 
  #remove duplicates
  filter(drug1 > drug2)

klaeger_combo_sets = possible_klaeger_combos %>% 
	mutate(klaeger_combo = pmap(list(drug1,drug2,concentration_M_d1,concentration_M_d2), ~calc_klaeger_combo_truncated(..1, ..2, ..3, ..4))) %>%
	unnest(klaeger_combo) %>%
	write_rds(here('results/ALMANAC_klaeger_models/klaeger_combos/klaeger_combos_for_validation_data.rds'))
```