```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(finetune)
library(vip)
library(ggridges)
library(patchwork)
```

```{r}
#read in data 
this_dataset = read_rds(here('results/ALMANAC_klaeger_L1000_data_for_ml.rds.gz'))
```


```{r}
set.seed(2222)
folds = vfold_cv(this_dataset, v = 5)

this_recipe = recipe(viability ~ ., this_dataset) %>%
  update_role(-starts_with("act_"),
              -starts_with("pert_"),
              -starts_with("viability"),
              new_role = "id variable") %>% 
  step_zv(all_predictors()) %>%
	step_normalize(all_predictors())

lr_spec = linear_reg(penalty = tune(), mixture = 1) %>%
	set_engine("glmnet") %>% 
	set_mode("regression")

lr_grid = grid_max_entropy(penalty(), size = 20)

this_wflow <-
	workflow() %>%
	add_model(lr_spec) %>%
	add_recipe(this_recipe)

race_ctrl = control_grid(
	save_pred = TRUE, 
	parallel_over = "everything",
	verbose = TRUE
)

results = tune_grid(
	this_wflow,
	resamples = folds,
	grid = lr_grid,
	control = race_ctrl
) %>% 
  collect_metrics() %>% 
	write_csv(here('results/ALMANAC_klaeger_L1000_models/feature_selection/lasso_tuning_results.csv'))

temp = read_csv(here('results/ALMANAC_klaeger_L1000_models/feature_selection/lasso_tuning_results.csv'))
```

```{r}
this_recipe = recipe(viability ~ ., this_dataset) %>%
  update_role(-starts_with("act_"),
              -starts_with("pert_"),
              -starts_with("viability"),
              new_role = "id variable") %>% 
  step_zv(all_predictors()) %>%
	step_normalize(all_predictors())

lr_final_spec = linear_reg(penalty = 2.024095e-06, mixture = 1) %>%
	set_engine("glmnet") %>% 
	set_mode("regression")

final_wflow <-
	workflow() %>%
	add_model(lr_final_spec) %>%
	add_recipe(this_recipe)

set.seed(2222)
final_results = 
	final_wflow %>% 
	fit(this_dataset)

all_importance = vi(final_results %>% extract_fit_parsnip()) %>%
	arrange(desc(Importance)) %>%
	filter(Importance > 0) %>% 
	mutate(rank = 1:n()) %>%
  rename(feature = Variable) %>% 
  mutate(feature_type = case_when(
    str_detect(feature, "^act_") ~ "Inhibition",
    str_detect(feature, "^pert_") ~ "Perturbed Transcriptomics",
    T ~ feature
  )) %>% 
	write_csv(here('results/ALMANAC_klaeger_L1000_models/feature_selection/lasso_selected_features.csv'))
```

```{r}
#lasso feature selection EDA

all_importance = read_csv(here('results/ALMANAC_klaeger_L1000_models/feature_selection/lasso_selected_features.csv'))

#preprocessing
all_importance_medians = all_importance %>% 
	group_by(feature_type) %>% 
	summarise(median = median(Importance, na.rm = TRUE)) %>% 
	arrange(desc(median))

all_importance_summary = all_importance %>% 
	mutate(feature_type = as.factor(feature_type)) %>%  
	mutate(feature_type = 
				 	fct_relevel(feature_type, 
				 							all_importance_medians$feature_type[1], 
				 							all_importance_medians$feature_type[2]))

per_group_rank = all_importance_summary %>%
	group_by(feature_type) %>%
	nest() %>%
	mutate(group_rank = map(data, ~ .x %>% 
														mutate(sub_percent_rank = percent_rank(Importance*-1),
																	 sub_rank = 1:n()))) %>%
	unnest(cols = c(group_rank)) %>%
	ungroup() %>%
	select(feature,sub_rank,sub_percent_rank) %>%
	identity()

all_importance_summary = all_importance_summary %>%
	left_join(per_group_rank)


#Pull out sample kinase inhibition correlations
sample_inhibitions = all_importance_summary %>%
	filter(feature_type == "Inhibition") %>%
	filter(sub_rank == 1 | sub_rank == 100 | sub_rank == 149)

ALMANAC_klaeger_samples = this_dataset %>%
	select(viability, sample_inhibitions$feature[1], sample_inhibitions$feature[2], sample_inhibitions$feature[3]) %>%
	pivot_longer(contains("act_"), names_to = "act_gene",values_to = "activation") %>%
	separate(act_gene, into = c("prefix","gene"),sep="_") %>% 
	mutate(gene = fct_relevel(gene, "FRK", "KLHL6", "EPHA5"))

activation_hex = ggplot(ALMANAC_klaeger_samples, aes(x=activation,y=viability)) +
	# geom_hex(fill = log10(..count..)) +
	stat_binhex(aes(fill=log10(..count..))) +
	geom_smooth(method = lm, color = 'red', lwd=1) +
	labs(x="Kinase Inhibition State",y="Cell Viability",fill="Log10\nData Points") +
	BerginskiRMisc::theme_berginski() +
	theme(aspect.ratio = 1:1, legend.text = element_text(size=8), legend.title = element_text(size=8)) +
	scale_x_continuous(breaks = c(0,.3,.6,1)) +
	scale_fill_viridis_c() +
	facet_wrap(~gene, scales = "free_x")

ggsave(here('figures/ALMANAC_klaeger_L1000/lasso_sample_activation_cor.png'),width=10.5,height=6, units = "cm")
```

```{r}
#Pull out sample L1000 correlations
sample_expressions = all_importance_summary %>%
	filter(feature_type == "Perturbed Transcriptomics") %>%
	filter(sub_rank == 1 | sub_rank == 400 | sub_rank == 1000)

ALMANAC_klaeger_samples = this_dataset %>%
	select(viability, sample_expressions$feature[1], sample_expressions$feature[2], sample_expressions$feature[3]) %>%
	pivot_longer(contains("pert_"), names_to = "act_gene",values_to = "expression") %>%
	separate(act_gene, into = c("prefix","gene"),sep="_") %>% 
	mutate(gene = fct_relevel(gene, "TWF2", "DMTF1", "PAFAH2"))

# PRISM_klaeger_samples %>%
# 	ggplot(aes(x=activation,y=ic50)) +
# 	geom_point(size=0,alpha=0.1) +
# 	geom_smooth(method = lm) +
# 	labs(x="Kinase expression State",y="IC50") +
# 	BerginskiRMisc::theme_berginski() +
# 	theme(aspect.ratio = 1:1) +
# 	facet_wrap(~gene, scales = "free_x")

activation_hex = ggplot(PRISM_klaeger_samples, aes(x=expression,y=viability)) +
	# geom_hex(fill = log10(..count..)) +
	stat_binhex(aes(fill=log10(..count..))) +
	geom_smooth(method = lm, color = 'red', lwd=1) +
	labs(x="L1000 Characteristic Direction",y="Cell Viability",fill="Log10\nData Points") +
	BerginskiRMisc::theme_berginski() +
	theme(aspect.ratio = 1:1, legend.text = element_text(size=8), legend.title = element_text(size=8)) +
	#scale_y_continuous(breaks = seq(0,1,by=0.25)) +
	scale_fill_viridis_c() +
	facet_wrap(~gene, scales = "free_x")

ggsave(here('figures/ALMANAC_klaeger_L1000/lasso_sample_perturbation_cor.png'),width=10.5,height=6, units = "cm")
```

```{r}
#ic50 plot

all_importance_summary %>% 
	ggplot(aes(x = Importance, y = feature_type, fill = factor(stat(quantile)))) +
	 stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE,
    quantiles = 4, quantile_lines = TRUE
  ) +
  scale_fill_viridis_d(name = "Quartiles") +
	theme_ridges(center_axis_labels = TRUE) + 
	labs(title = " ",x = "Lasso Coefficient Size", y = "Data Type") +
  coord_cartesian(clip = "off")
	
ggsave(here('figures/ALMANAC_klaeger_L1000/lasso_correlations.png'), height = 6, width = 21, units = "cm")
```



