---
title: "Find LINCS-Klaeger Drug Matches"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(readxl)

knitr::opts_knit$set(root.dir = here())
```


```{r}
klaeger = read_rds(here('results/klaeger_full_tidy.rds'))

klaeger_match_set = data.frame(
	drug = sort(unique(trimws(klaeger$drug)))
) %>% mutate(lower_case_drug = tolower(drug)) %>%
	mutate(no_dash_drug = str_replace(drug,"-",""))

LINCS = read_xlsx(here('data/HMS-LINCS_KinomeScan_Datasets_2018-01-18.xlsx'))
# 
# LINCS_match_set = LINCS %>%
# 	select(sm_name, sm_alternative_names) %>%
# 	mutate(sm_name = trimws(sm_name), sm_alternative_names = trimws(sm_alternative_names)) %>%
#   rename('name' = sm_name, 'alt_name' = sm_alternative_names) %>% 
# 	unique() %>%
# 	filter(!is.na(name))

LINCS_match_set = LINCS %>%
	select(sm_name) %>%
	mutate(sm_name = trimws(sm_name)) %>%
  rename('name' = sm_name) %>% 
	unique() %>%
	filter(!is.na(name))

matches = LINCS_match_set %>%
	left_join(klaeger_match_set, by = c('name'='drug')) %>%
	left_join(klaeger_match_set, by = c('name'='lower_case_drug')) %>%
	left_join(klaeger_match_set, by = c('name'='no_dash_drug')) %>%
  column_to_rownames(var = "name") %>% 
  filter(if_any(everything(), ~!is.na(.))) %>%
  rownames_to_column(var = "name") %>% 
	identity()

# klaeger_no_matches = klaeger_match_set %>%
# 	filter(!drug %in% matches$name)

LINCS_no_matches = LINCS_match_set %>%
	filter(!name %in% matches$name)

write_csv(klaeger_match_set, here('src/find_LINCS_klaeger_matches/no_clear_match_klaeger_drug_list.csv'))
write_csv(as.data.frame(LINCS_no_matches), here('src/find_LINCS_klaeger_matches/no_clear_match_LINCS_drug_list.csv'))
```

From here we opened each individual drug list file and manually matched the drug names, producing "manual_matches.csv". 

```{r}
manual_matches = read_csv(here('src/find_PRISM_klaeger_matches/manual_matches.csv'))

manual_matches = manual_matches %>%
	left_join(PRISM_match_set, by = c('PRISM_name'='name'))

combined_match_list = matches %>%
	mutate(manual_match_broad_id = NA) %>%
	# select(drug,broad_id) %>%
	bind_rows(manual_matches %>%
							select(-PRISM_name) %>%
							rename(drug = klaeger_drug, manual_match_broad_id = broad_id)) %>%
	mutate(broad_id = ifelse(is.na(broad_id), manual_match_broad_id, broad_id)) %>%
	select(everything(),manual_match_broad_id,broad_id) %>%
	write_csv(here('src/find_PRISM_klaeger_matches/klaeger_PRISM_match_list.csv'))

unmatched_klaeger = klaeger_match_set %>% 
		filter(! drug %in% combined_match_list$drug) %>% 
		select(drug) %>% 
		select(klaeger_drug = drug)
unmatched_PRISM = PRISM_match_set %>%
	filter(! broad_id %in% combined_match_list$broad_id)

write_csv(unmatched_klaeger,here('src/find_PRISM_klaeger_matches/unmatched_klaeger.csv'))
write_csv(unmatched_PRISM,here('src/find_PRISM_klaeger_matches/unmatched_PRISM.csv'))
```