```{r}
#setup
library(tidyverse)
library(patchwork)
library(here)
```

```{r}
#read in modelling results 

cancer_type = c("breast",
                 "lung",
                 "ovarian",
                 "melanoma",
                 "colon",
                 "cns",
                 "renal",
                 "prostate")

model_type = c("xgboost", "random forest")

data_paths = crossing(cancer_type, model_type) %>% 
  as.data.frame() %>% 
  mutate(data_path = 
           if_else(model_type == "random forest",
              here('results/ALMANAC_klaeger_models',
                          paste0(cancer_type, '_cancer_models'),
                          paste0('ALMANAC_klaeger_lasso_xgboost_all_tuning_results_rf.csv')),
              here('results/ALMANAC_klaeger_models',
                          paste0(cancer_type, '_cancer_models'),
                          paste0('ALMANAC_klaeger_lasso_xgboost_all_tuning_results.csv'))
           )
  )

#add pan cancer model and ALMANAC klaeger Johnson breast cancer results
data_paths_combined = data_paths %>%
  filter(cancer_type != "breast") %>% 
  bind_rows(tribble(
    ~cancer_type, ~model_type, ~data_path,
                    "breast", "xgboost",
    here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/ALMANAC_klaeger_johnson_lasso_xgboost_all_tuning_results_all_kinases_forced_in.csv'),
                    "pan-cancer", "xgboost",
    here('results/ALMANAC_klaeger_johnson_models/pan_cancer_models/ALMANAC_klaeger_johnson_lasso_xgboost_all_tuning_results_truncated.csv'),
    "breast", "random forest",
    here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/ALMANAC_klaeger_johnson_lasso_xgboost_all_tuning_results_all_kinases_forced_in_rf.csv'),
    "pan-cancer", "random forest",
    here('results/ALMANAC_klaeger_johnson_models/pan_cancer_models/ALMANAC_klaeger_johnson_lasso_xgboost_all_tuning_results_truncated_rf.csv')
    )
  )
  

plot_data = data.frame()
for (i in 1:dim(data_paths_combined)[1]) {
  
  this_data_path = data_paths_combined$data_path[i]
  this_cancer_type = data_paths_combined$cancer_type[i]
  this_model_type = data_paths_combined$model_type[i]
  
  this_plot_data = read_csv(this_data_path) %>%
    mutate(cancer_type = this_cancer_type,
           model_type = this_model_type) %>% 
    arrange(desc(mean)) %>% 
    slice(1)
  plot_data = bind_rows(plot_data, this_plot_data)
}

```

```{r}
#make plot

plot_data %>% 
  select(-tree_depth) %>% 
  arrange(desc(mean)) %>% 
  mutate(cancer_type = fct_inorder(cancer_type)) %>% 
  ggplot(aes(x = cancer_type, y = mean, colour = cancer_type, shape = model_type)) + 
  geom_point() +
  facet_wrap(vars(model_type)) +
  labs(x = "Cancer Type", y = "R-squared", colour = "Cancer Type", shape = "Model Type") +
		theme(
		axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
		legend.position = "none",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )
ggsave(here('figures/ALMANAC_klaeger/all_model_comparisons.png'), width = 14, height = 8, units = "cm")
```

