---
title: "Build model predicitons on non-tested data"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)
library(ROCR)
library(reticulate)
library(vip)
library(recipeselectors)
library(conflicted)
library(Metrics)

conflict_prefer("slice", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("rmse", "Metrics")
conflict_prefer("vi", "vip")
knitr::opts_knit$set(root.dir = here())
```

```{r}
ALMANAC_klaeger_CCLE_data = read_rds(here('results/ALMANAC_klaeger_models/breast_cancer_models/ALMANAC_klaeger_data_for_ml_breast.rds.gz'))
not_tested_data = read_rds(here('results/ALMANAC_klaeger_models/breast_cancer_models/not_tested_data.rds.gz'))
final_model = read_rds(here('results/ALMANAC_klaeger_models/breast_cancer_models/final_model.rds.gz'))
```

```{r}
model_predictions = augment(final_model, not_tested_data %>% 
                              mutate(PANEL = NA, CELLNAME = NA, nearest_klaeger_dose_1 = NA, nearest_klaeger_dose_2 = NA)) %>% 
	select(-starts_with("act_"), -starts_with("exp_"))

model_predictions_tidy = model_predictions %>%
  select(-PANEL, -CELLNAME) %>% 
	mutate(predicted_viability = signif(.pred,3)) %>%
	write_csv(here('results/ALMANAC_klaeger_models/breast_cancer_models/final_model_predictions.csv'))
```

