```{r}
library(tidyverse)
library(here)
library(synergyfinder)
library(patchwork)
library(Metrics)
library(wesanderson)
```

## Load data

```{r}
prediction_data <- read_csv(here("results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation/model_predictions_all_kinases_forced_in.csv"))
validation_data <- read_csv(here("results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation/validation_klaeger_exp_data_for_all_kinases_forced_in.csv"))
```

## Reshape both datasets

```{r}
# Reshape prediction_data
prediction_pair_indicies <- prediction_data %>%
    select(drug1, drug2, cell_line) %>%
    unique() %>%
    mutate(pair_index = 1:n())

prediction_processed <- prediction_data %>%
    left_join(prediction_pair_indicies, by = c("drug1", "drug2", "cell_line")) %>%
    mutate(conc_unit = "M") %>%
    rename(conc1 = nearest_klaeger_dose_1, conc2 = nearest_klaeger_dose_2, response = viability) %>%
    select(pair_index, drug1, drug2, conc1, conc2, conc_unit, response) %>%
    mutate(response = response * 100)

prediction_reshaped <- ReshapeData(
    data = prediction_processed,
    data_type = "viability",
    impute = TRUE,
    impute_method = NULL,
    noise = TRUE,
    seed = 1
)
```

```{r}
# Reshape validation_data
validation_pair_indicies <- validation_data %>%
    select(drug1, drug2, cell_line) %>%
    unique() %>%
    mutate(pair_index = 1:n())

validation_processed <- validation_data %>%
    left_join(validation_pair_indicies, by = c("drug1", "drug2", "cell_line")) %>%
    mutate(conc_unit = "M") %>%
    rename(conc1 = nearest_klaeger_dose_1, conc2 = nearest_klaeger_dose_2, response = viability) %>%
    select(pair_index, drug1, drug2, conc1, conc2, conc_unit, response) %>%
    mutate(response = response * 100)

validation_reshaped <- ReshapeData(
    data = validation_processed,
    data_type = "viability",
    impute = TRUE,
    impute_method = NULL,
    noise = TRUE,
    seed = 1
)
```

## Calculate synergy and sensitivity scores

```{r}
# Calculate synergy and sensitivity scores for prediction_data
prediction_synergy_scores <- CalculateSynergy(
    data = prediction_reshaped,
    method = c("ZIP", "HSA", "Bliss", "Loewe"),
    Emin = NA,
    Emax = NA,
    correct_baseline = "non"
)

prediction_sensitivity_scores <- prediction_synergy_scores %>%
    CalculateSensitivity(correct_baseline = "non")

# Calculate synergy and sensitivity scores for validation_data
validation_synergy_scores <- CalculateSynergy(
    data = validation_reshaped,
    method = c("ZIP", "HSA", "Bliss", "Loewe"),
    Emin = NA,
    Emax = NA,
    correct_baseline = "non"
)

validation_sensitivity_scores <- validation_synergy_scores %>%
    CalculateSensitivity(correct_baseline = "non")
```

```{r}
# Visualize Synergy-Sensitivity Scores
PlotSensitivitySynergy(
    data = prediction_sensitivity_scores,
    plot_synergy = "ZIP",
    show_labels = TRUE,
    dynamic = FALSE
)

PlotSensitivitySynergy(
    data = validation_sensitivity_scores,
    plot_synergy = "ZIP",
    show_labels = TRUE,
    dynamic = FALSE
)
```

```{r}
# Plot Trametinib Omipalisib synergy

Plot2DrugHeatmap(
    data = validation_synergy_scores,
    plot_block = 28,
    drugs = c(1, 2),
    plot_value = "ZIP_synergy",
    dynamic = FALSE,
    summary_statistic = c("quantile_25", "quantile_75")
)

Plot2DrugHeatmap(
    data = prediction_synergy_scores,
    plot_block = 28,
    drugs = c(1, 2),
    plot_value = "ZIP_synergy",
    dynamic = FALSE,
    summary_statistic = c("quantile_25", "quantile_75")
)
```

```{r}
#Similarly extract synergy scores and sensitivites for all "block_id" present in prediction and validation data

prediction_synergy_scores_all <- prediction_sensitivity_scores$synergy_scores %>%
    write_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/prediction_synergy_scores_all.csv'))

prediction_sensitivity_scores_all <- prediction_sensitivity_scores$response %>%
    write_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/prediction_sensitivity_scores_all.csv'))

validation_synergy_scores_all <- validation_sensitivity_scores$synergy_scores %>%
    write_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation_synergy_scores_all.csv'))

validation_sensitivity_scores_all <- validation_sensitivity_scores$response %>% 
    write_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation_sensitivity_scores_all.csv'))
```

```{r}
#Read in synergy scores and metdata
prediction_data <- read_csv(here("results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation/model_predictions_all_kinases_forced_in.csv"))
validation_data <- read_csv(here("results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation/validation_klaeger_exp_data_for_all_kinases_forced_in.csv"))

prediction_block_ids <- prediction_data %>%
    select(drug1, drug2, cell_line) %>%
    unique() %>%
    mutate(block_id = 1:n())

validation_block_ids <- validation_data %>%
    select(drug1, drug2, cell_line) %>%
    unique() %>%
    mutate(block_id = 1:n())    

prediction_synergy_scores_all = read_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/prediction_synergy_scores_all.csv'))

prediction_sensitivity_scores_all = read_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/prediction_sensitivity_scores_all.csv'))

validation_synergy_scores_all = read_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation_synergy_scores_all.csv'))

validation_sensitivity_scores_all = read_csv(here('results/ALMANAC_klaeger_johnson_models/breast_cancer_models/validation_sensitivity_scores_all.csv'))
```

```{r}
#Find accuracy metrics for all types of synergy metrics
predicted_vs_validated_synergy_scores = prediction_synergy_scores_all  %>%
    left_join(prediction_block_ids)  %>%
    select(block_id, drug1, drug2, conc1, conc2, ZIP_synergy, HSA_synergy, Loewe_synergy, Bliss_synergy)  %>% 
    rename(ZIP_synergy_predicted = ZIP_synergy,
           HSA_synergy_predicted = HSA_synergy,
           Loewe_synergy_predicted = Loewe_synergy, 
           Bliss_synergy_predicted = Bliss_synergy)  %>% 
    left_join(validation_synergy_scores_all %>%
                  left_join(validation_block_ids)  %>%  
                  select(block_id, drug1, drug2, conc1, conc2, ZIP_synergy, HSA_synergy, Loewe_synergy, Bliss_synergy)  %>% 
                  rename(ZIP_synergy_validated = ZIP_synergy, 
                         HSA_synergy_validated = HSA_synergy, 
                         Loewe_synergy_validated = Loewe_synergy, 
                         Bliss_synergy_validated = Bliss_synergy), 
              by = c("drug1", "drug2", "conc1", "conc2"))  %>% 
    pivot_longer(
        any_of(c("ZIP_synergy_predicted", 
                 "HSA_synergy_predicted", 
                 "Loewe_synergy_predicted", 
                 "Bliss_synergy_predicted", 
                 "ZIP_synergy_validated", 
                 "HSA_synergy_validated", 
                 "Loewe_synergy_validated", 
                 "Bliss_synergy_validated")), 
        names_to = "synergy_metric", 
        values_to = "synergy_score")  %>%
    mutate(metric_type = if_else(str_detect(synergy_metric, "predicted"), "predicted_score", "validated_score"))  %>%  
    mutate(synergy_metric = str_replace(synergy_metric, "_predicted", ""), 
           synergy_metric = str_replace(synergy_metric, "_validated", ""), 
           synergy_metric = str_replace(synergy_metric, "synergy", ""), 
           synergy_metric = str_replace(synergy_metric, "_", " "))  %>% 
    mutate(synergy_metric = trimws(synergy_metric, which = c("both")))  %>% 
    filter(conc1 != 0 & conc2 != 0)  %>% 
    pivot_wider(names_from = metric_type, values_from = synergy_score)  %>% 
    drop_na()

#Get accuracy metrics via R-squared for each synergy metric
metrics_compared = c("ZIP", "HSA", "Loewe", "Bliss")

all_individual_metrics = data.frame()
for(i in 1:length(metrics_compared)) {

this_metric = metrics_compared[i]
  
this_metric_predictions = predicted_vs_validated_synergy_scores %>% 
  filter(synergy_metric == this_metric)

this_rsq = cor(this_metric_predictions$validated_score, this_metric_predictions$predicted_score)^2

this_rmse = rmse(this_metric_predictions$validated_score, this_metric_predictions$predicted_score)

this_metrics = data.frame(this_rsq, this_rmse, this_metric)

all_individual_metrics = bind_rows(all_individual_metrics, this_metrics)

}

all_individual_metrics_arranged = all_individual_metrics %>%
  arrange(desc(this_rsq))

#join in individual metric accuracies
predicted_vs_validated_synergy_scores_for_plot = predicted_vs_validated_synergy_scores %>%
  left_join(all_individual_metrics_arranged, by = c("synergy_metric" = "this_metric"))  %>% 
  mutate(this_rsq = paste0("R\u00B2 = ", round(this_rsq, 2), " / RMSE = ", round(this_rmse, 2)),
         this_label = paste0(synergy_metric, " Prediction Accuracy"))  %>% 
  mutate(this_label = fct_relevel(this_label, levels = c("HSA Prediction Accuracy",
                                                         "Loewe Prediction Accuracy",
                                                         "ZIP Prediction Accuracy", 
                                                         "Bliss Prediction Accuracy")))


predicted_vs_validated_synergy_scores_for_plot  %>% 
	ggplot(aes(x = predicted_score, y = validated_score)) +
	geom_jitter() +
	geom_smooth(method = "lm", color = wes_palettes$GrandBudapest1[2]) +
	geom_abline(intercept = 0, slope = 1, size = 0.5, colour = 'black', linetype = 3) +
	labs(
	  x = "Predicted Synergy Score",
	  y = "Experimental Synergy Score") +
	theme(
		panel.background = element_rect(fill = "transparent",colour = NA),
		panel.grid.minor = element_blank(), 
		panel.grid.major = element_blank(),
		plot.background = element_rect(fill = "transparent",colour = NA)
	) +
  facet_wrap(~ this_label + this_rsq)

ggsave(here("figures/ALMANAC_klaeger_johnson/synergy_prediction_accuracy_by_metric_type.png"), width = 9, height = 8, units = "cm", dpi = 300)

```

```{r}
# extract synergy scores for trametinib and omipalisib for comparison

prediction_tram_omi_synergy <- prediction_synergy_scores_all %>%
    filter(block_id == 28)

validation_tram_omi_synergy <- validation_synergy_scores_all %>%
    filter(block_id == 28)

prediction_tram_omi_sensitivity <- prediction_sensitivity_scores_all %>%
    filter(block_id == 28)

validation_tram_omi_sensitivity <- validation_sensitivity_scores_all %>%
    filter(block_id == 28)
  
# Make heatmap plots comparing synergy for trametinib and omipalisib in model predictions vs validation
prediction_synergy_plot <- prediction_tram_omi_synergy %>%
    mutate(type = "Predicted Synergy") %>%
    ggplot(aes(factor(conc1), factor(conc2), fill = ZIP_synergy)) +
    geom_tile() +
    scale_fill_viridis_c() +
    labs(
        x = "Trametinib (M)",
        y = "Omipalisib (M)",
        fill = "Synergy\n(ZIP)"
    ) +
    theme(
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
        panel.background = element_rect(fill = "transparent", colour = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA)
    ) +
    facet_wrap(~type)

prediction_sensitivity_plot <- prediction_tram_omi_sensitivity %>%
    mutate(type = "Predicted Sensitivity") %>%
    ggplot(aes(factor(conc1), factor(conc2), fill = response_origin)) +
    geom_tile() +
    scale_fill_viridis_c() +
    labs(
        x = "Trametinib (M)",
        y = "Omipalisib (M)",
        fill = "Sensitivity\n(Viability)"
    ) +
    theme(
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
        panel.background = element_rect(fill = "transparent", colour = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA)
    ) +
    facet_wrap(~type)

prediction_plot <- prediction_synergy_plot / prediction_sensitivity_plot + plot_annotation(title = "Predicted Trametinib + Omipalisib Synergy and Sensitivity")

validation_synergy_plot <- validation_tram_omi_synergy %>%
    mutate(type = "Actual Synergy") %>%
    ggplot(aes(factor(conc1), factor(conc2), fill = ZIP_synergy)) +
    geom_tile() +
    scale_fill_viridis_c() +
    labs(
        x = "Trametinib (M)",
        y = "Omipalisib (M)",
        fill = "Synergy\n(ZIP)"
    ) +
    theme(
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
        panel.background = element_rect(fill = "transparent", colour = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA)
    ) +
    facet_wrap(~type)

validation_sensitivity_plot <- validation_tram_omi_sensitivity %>%
    mutate(type = "Actual Sensitivity") %>%
    ggplot(aes(factor(conc1), factor(conc2), fill = response_origin)) +
    geom_tile() +
    scale_fill_viridis_c() +
    labs(
        x = "Trametinib (M)",
        y = "Omipalisib (M)",
        fill = "Sensitivity\n(Viability)"
    ) +
    theme(
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm"),
        panel.background = element_rect(fill = "transparent", colour = NA),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA), 
        text = element_text(size = 10)
    ) +
    facet_wrap(~type)

validation_plot <- validation_synergy_plot / validation_sensitivity_plot + plot_annotation(title = "Actual Trametinib + Omipalisib Synergy and Sensitivity")

full_plot <- prediction_plot | validation_plot
#ggsave(here("figures/ALMANAC_klaeger_johnson/tram_omi_predicted_synergy_sensitivity_for_poster.png"), width = 6, height = 4, units = "in")
ggsave(here("figures/ALMANAC_klaeger_johnson/tram_omi_predicted_synergy_sensitivity.png"), width = 12, height = 8, units = "cm", dpi = 300)

```