```{r}
library(tidyverse)
library(here)
library(umap)
```

```{r}
# read in data
klaeger_tidy <- read_rds(here("results/klaeger_full_tidy.rds"))
klaeger_combinations_validation <- read_rds(here("results/ALMANAC_klaeger_models/klaeger_combos/klaeger_combos_for_validation_data.rds"))
klaeger_combinations <- read_rds(here("results/ALMANAC_klaeger_models/klaeger_combos/all_klaeger_combos.rds.gz"))
```

```{r}
# pick out combo of trametinib and dabrafenib at 1uM for plotting

tram_dab_data <- klaeger_combinations_validation %>%
  filter(drug1 == "Trametinib" & drug2 == "Dabrafenib") %>%
  filter((concentration_M_d1 == 1 * 10^(-6) | concentration_M_d1 == 0) & (concentration_M_d2 == 1 * 10^(-6) | concentration_M_d2 == 0)) %>%
  pivot_longer(starts_with("act_"), names_to = "Kinase", values_to = "Inhibition")

kinases_to_keep <- tram_dab_data %>%
  group_by(Kinase) %>%
  summarise(mean = mean(Inhibition)) %>%
  filter(mean < 1)

tram_dab_data_for_plot <- tram_dab_data %>%
  filter(Kinase %in% kinases_to_keep$Kinase) %>%
  filter(!(concentration_M_d1 == 0 & concentration_M_d2 == 0)) %>%
  mutate(treatment = paste0(as.character(concentration_M_d1), " ", drug1, " + ", as.character(concentration_M_d2), " ", drug2)) %>%
  mutate(treatment = case_when(
    treatment == "1e-06 Trametinib + 1e-06 Dabrafenib" ~ "Trametinib + Dabrafenib",
    treatment == "0 Trametinib + 1e-06 Dabrafenib" ~ "Dabrafenib",
    treatment == "1e-06 Trametinib + 0 Dabrafenib" ~ "Trametinib",
    TRUE ~ treatment
  )) %>%
  mutate(treatment = fct_relevel(treatment, c("Trametinib + Dabrafenib", "Dabrafenib", "Trametinib")))
```

```{r}
tram_dab_data_for_plot %>%
  ggplot(aes(Kinase, treatment, fill = Inhibition)) +
  geom_tile() +
  scale_fill_viridis_c() +
  theme(
    legend.position = "right",
    legend.direction = "vertical",
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 12),
    axis.ticks.x = element_blank(),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_blank(),
    panel.background = element_rect(fill = "transparent", colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
ggsave(here("figures/combined_inhibition_state_visual.png"), width = 21, height = 3, units = "cm")
```

```{r}
# prep klaeger_combo data for UMAP, filtering to only include 1uM
klaeger_combinations_for_umap <- klaeger_combinations %>%
  mutate(treatment = paste0(drug1, " + ", drug2)) %>%
  select(-concentration_M_d1, -concentration_M_d2, -drug1, -drug2) %>% 
  mutate(origin = "Combination Therapy")

# prep klaeger monotherapy data for UMAP, filtering to only include 1uM
klaeger_monotherapy_for_umap <- klaeger_tidy %>%
  filter(concentration_M == 1 * 10^(-6)) %>%
  rename(treatment = drug) %>%
  mutate(gene_name = paste0("act_", gene_name)) %>%
  # pivot to wide
  pivot_wider(names_from = gene_name, values_from = relative_intensity) %>%
  select(-concentration_M) %>% 
  mutate(origin = "Monotherapy")

# Combine monotherapy and combo data

klaeger_for_umap <- klaeger_combinations_for_umap %>%
  bind_rows(klaeger_monotherapy_for_umap) %>%
  mutate(id = row_number())

# remove kinases with zero variance
zv_kinases <- klaeger_for_umap %>%
  select(starts_with("act_")) %>%
  pivot_longer(everything(), names_to = "kinase", values_to = "relative_intensity") %>%
  group_by(kinase) %>%
  summarise(var = var(relative_intensity)) %>%
  filter(var == 0)
```

```{r}
#Make similar visual for klaeger monotherapy data
dabrafenib_data <- klaeger_tidy %>%
  filter(drug == "Dabrafenib") %>%
  filter(concentration_M == 1 * 10^(-6))

kinases_to_keep_dabrafenib <- dabrafenib_data %>%
  group_by(gene_name) %>%
  summarise(mean = mean(relative_intensity)) %>%
  filter(mean < 1)

dabrafenib_data_for_plot <- dabrafenib_data %>% 
  filter(gene_name %in% kinases_to_keep_dabrafenib$gene_name) %>%
  rename(treatment = drug, Kinase = gene_name, Inhibition = relative_intensity)

 #Make plot with all font sizes and colors consistent
dabrafenib_data_for_plot  %>% 
  ggplot(aes(treatment, Kinase, fill = Inhibition)) +
  geom_tile() +
  scale_fill_viridis_c() +
  theme(
    legend.position = "right",
    legend.direction = "vertical",
    axis.text.x = element_text(size = 11),
    axis.ticks.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_text(size = 10),
    panel.background = element_rect(fill = "transparent", colour = NA),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent", colour = NA)
  )
ggsave(here("figures/monotherapy_inhibition_state_visual.png"), width = 5, height = 15, units = "cm")
```

```{r}
# Perform UMAP on klaeger monotherapy data

klaeger_for_umap_meta <- klaeger_for_umap %>%
  select(id, treatment, origin) 

set.seed(2222)
klaeger_umap_fit <- klaeger_for_umap %>%
  select(id, starts_with("act_")) %>%
  column_to_rownames("id") %>%
  select(-any_of(zv_kinases$kinase)) %>%
  scale() %>%
  as.data.frame() %>%
  drop_na() %>%
  as.matrix() %>%
  umap()

klaeger_umap_df <- klaeger_umap_fit$layout %>%
  as.data.frame() %>%
  rename(
    UMAP1 = "V1",
    UMAP2 = "V2"
  ) %>%
  mutate(id = row_number()) %>%
  inner_join(klaeger_for_umap_meta, by = "id")
```

```{r}
#make klaeger monotherapy vs combo therapy umap plot
klaeger_umap_df %>%
  ggplot(aes(x = UMAP1, 
             y = UMAP2, 
             colour = origin)) +
	geom_jitter() +
	scale_colour_brewer(type = "qual") +
	#facet_wrap(vars(origin), scales = "free") +
  labs(x = "UMAP1",
       y = "UMAP2",
  		 colour = "Treatment Type",
      title = "Kinome Target Space") +
	theme(
		legend.position = "right",
		legend.text = element_text(size = 9),
		legend.background = element_rect(fill = "transparent",colour = NA),
		panel.background = element_rect(fill = "transparent",colour = NA),
    panel.grid.minor = element_blank(), 
    panel.grid.major = element_blank(),
    plot.background = element_rect(fill = "transparent",colour = NA)
      )

	ggsave(here("figures/clustering/combo_vs_monotherapy_kinome_space_UMAP.png"), width = 21, height = 12, units = "cm")
```