---
title: "prep_ALMANAC_klaeger_data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(purrr)
library(ggridges)
```

```{r}
#read in data 

ALMANAC = read_csv(here('results/ALMANAC_klaeger_models/ALMANAC_processed.csv'))
matched_ALMANAC_drugs = read_csv(here('src/data_organization/find_ALMANAC_klaeger_matches/ALMANAC_klaeger_matchlist.csv'))
CCLE_data = read_rds(here('data/full_CCLE_expression_set_for_ML.rds'))
ALMANAC_PRISM_cell_line_matches = read_csv(here('src/data_organization/find_ALMANAC_klaeger_matches/manual_matched_cell_lines.csv'))
klaeger_combinations = read_rds(here('results/ALMANAC_klaeger_models/klaeger_combos/klaeger_synergy_combos_simple.rds')) %>% 
	filter(drug_1 %in% matched_ALMANAC_drugs$klaeger_name | drug_2 %in% matched_ALMANAC_drugs$klaeger_name)

```

```{r}
#matching doses and cell line names
klaeger_doses = klaeger_combinations %>% 
	select(concentration_M_d1, concentration_M_d2) %>% 
	unique()

ALMANAC_cell_line_matched = ALMANAC %>%
	left_join(ALMANAC_PRISM_cell_line_matches, by = c('CELLNAME' = 'ALMANAC_NAME')) %>% 
	select(-PRISM_NAME) %>% 
	filter(DepMap_ID %in% CCLE_data$DepMap_ID) %>% 
	select(PANEL, CELLNAME, CONC1, CONC2, viability, drug1, drug2, DepMap_ID)

ALMANAC_doses = ALMANAC_cell_line_matched %>% 
	group_by(CONC1, CONC2) %>% 
	summarise(n = n())

dose_matches = ALMANAC_doses %>% 
	inner_join(klaeger_doses, by = c('CONC1' = 'concentration_M_d2', 'CONC2' = 'concentration_M_d1'))
	
write_csv(dose_matches, here('results/ALMANAC_klaeger_models/ALMANAC_klaeger_dose_matches.csv'))
```


```{r}
#find nearest concentrations for matching

ALMANAC_unique_doses_1 = ALMANAC_doses %>%
	ungroup() %>% 
	select(CONC1) %>%
	rename(conc = CONC1) %>% 
	unique()
ALMANAC_unique_doses_2 = ALMANAC_doses %>%
	ungroup() %>% 
	select(CONC2) %>% 
	rename(conc = CONC2) %>% 
	unique()
ALMANAC_unique_doses = bind_rows(
	ALMANAC_unique_doses_1, ALMANAC_unique_doses_2
) %>% 
	unique()

klaeger_unique_doses = klaeger_doses %>% 
	select(concentration_M_d1) %>% 
	rename(conc = concentration_M_d1) %>% 
	unique()

matched_doses = ALMANAC_unique_doses %>% 
	filter(conc %in% klaeger_unique_doses$conc) %>% 
	mutate(klaeger_conc = conc)

ALMANAC_unmatched_doses = ALMANAC_unique_doses %>% 
	filter(!conc %in% matched_doses$conc)

nearest_klaeger_concentration = function(concentration, all_klaeger_concentrations) {
differences = all_klaeger_concentrations %>% 
	filter(conc != 0) %>% 
	mutate('difference' = abs(conc - concentration)) %>%  
	arrange(difference) 
min_difference = differences$conc[1]
return(min_difference)
}

ALMANAC_nearest_klaeger_doses = ALMANAC_unmatched_doses %>% 
	mutate(nearest_klaeger_dose = map(conc, ~nearest_klaeger_concentration(., klaeger_unique_doses))) %>% 
	as.data.frame() %>% 
	unnest(cols = c(nearest_klaeger_dose))

write_csv(ALMANAC_nearest_klaeger_doses, here('results/ALMANAC_klaeger_models/ALMANAC_nearest_klaeger_doses.csv'))

```

```{r}

ALMANAC_combos = ALMANAC_cell_line_matched %>% 
	select(drug1, drug2) %>% 
	unique() %>% 
	filter(drug1 > drug2)

ALMANAC_cell_line_matched_unique = data.frame()
for (i in 1:dim(ALMANAC_combos)[1]) {
	this_drug_1 = ALMANAC_combos$drug1[i]
	this_drug_2 = ALMANAC_combos$drug2[i]

	this_data = ALMANAC_cell_line_matched %>% 
		filter(drug1 == this_drug_1 | drug2 == this_drug_1) %>% 
		filter(drug1 == this_drug_2 | drug2 == this_drug_2) %>% 
		group_by(DepMap_ID, PANEL, CELLNAME, CONC1, CONC2) %>%
		summarise(viability = mean(viability)) %>% 
		mutate(drug1 = this_drug_1, drug2 = this_drug_2) %>% 
		select(PANEL, CELLNAME, DepMap_ID, drug1, drug2, CONC1, CONC2, viability)

	ALMANAC_cell_line_matched_unique = bind_rows(ALMANAC_cell_line_matched_unique, this_data)	%>% 
		unique()
	
}

ALMANAC_klaeger_data =  ALMANAC_cell_line_matched_unique %>%
	left_join(ALMANAC_nearest_klaeger_doses, by = c('CONC1' = 'conc')) %>% 
	rename(nearest_klaeger_dose_1 = nearest_klaeger_dose) %>% 
	left_join(matched_doses, by = c('CONC1' = 'conc')) %>% 
	mutate(nearest_klaeger_dose_1 = if_else(
		is.na(nearest_klaeger_dose_1), 
		klaeger_conc, 
		nearest_klaeger_dose_1
	)) %>% 
	select(-klaeger_conc) %>% 
	left_join(ALMANAC_nearest_klaeger_doses, by = c('CONC2' = 'conc')) %>% 
	rename(nearest_klaeger_dose_2 = nearest_klaeger_dose) %>% 
	left_join(matched_doses, by = c('CONC2' = 'conc')) %>% 
	mutate(nearest_klaeger_dose_2 = if_else(
		is.na(nearest_klaeger_dose_2), 
		klaeger_conc, 
		nearest_klaeger_dose_2
	)) %>% 
	select(-klaeger_conc) %>% 
	left_join(klaeger_combinations, 
						by = c('drug1' = 'drug_1',
									 'drug2' = 'drug_2',
									 'nearest_klaeger_dose_1' = 'concentration_M_d1',
									 'nearest_klaeger_dose_2' = 'concentration_M_d2')) %>% 
	drop_na()

# ALMANAC_klaeger_data %>% count(drug1, drug2) %>% view()
# klaeger_combinations %>% select(drug_1, drug_2) %>% unique() %>% view()
```

```{r}

#join in CCLE data 

ALMANAC_klaeger_CCLE_data = ALMANAC_klaeger_data %>% 
	left_join(CCLE_data, by = 'DepMap_ID') %>% 
	drop_na()

```


```{r}
set.seed(2222)
#excluding viability > 1
this_dataset = ALMANAC_klaeger_CCLE_data %>% 
	filter(viability <=1)
```

```{r}

write_csv(this_dataset, here('results/ALMANAC_klaeger_data_for_ml.csv'))

```

```{r}
#EDA
disease_count = this_dataset %>% 
  select(PANEL, CELLNAME) %>% 
  unique() %>% 
  group_by(PANEL) %>% 
  summarise(n = n())

 combo_count = this_dataset %>% 
  select(drug1, drug2) %>% 
  unique()

 cell_count = this_dataset %>% 
  select(CELLNAME) %>% 
  unique() 
```

```{r}
#write out individual cancer data
lung_cancer_data = this_dataset %>% 
  filter(PANEL == "Non-Small Cell Lung Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/lung_cancer_models/ALMANAC_klaeger_data_for_ml_lung.rds.gz'), compress = "gz")

breast_cancer_data = this_dataset %>% 
  filter(PANEL == "Breast Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/breast_cancer_models/ALMANAC_klaeger_data_for_ml_breast.rds.gz'), compress = "gz")

melanoma_cancer_data = this_dataset %>% 
  filter(PANEL == "Melanoma") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/melanoma_cancer_models/ALMANAC_klaeger_data_for_ml_melanoma.rds.gz'), compress = "gz")

ovarian_cancer_data = this_dataset %>% 
  filter(PANEL == "Ovarian Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/ovarian_cancer_models/ALMANAC_klaeger_data_for_ml_ovarian.rds.gz'), compress = "gz")

cns_cancer_data = this_dataset %>% 
  filter(PANEL == "CNS Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/cns_cancer_models/ALMANAC_klaeger_data_for_ml_cns.rds.gz'), compress = "gz")

colon_cancer_data = this_dataset %>% 
  filter(PANEL == "Colon Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/colon_cancer_models/ALMANAC_klaeger_data_for_ml_colon.rds.gz'), compress = "gz")

renal_cancer_data = this_dataset %>% 
  filter(PANEL == "Renal Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/renal_cancer_models/ALMANAC_klaeger_data_for_ml_renal.rds.gz'), compress = "gz")

leukemia_cancer_data = this_dataset %>% 
  filter(PANEL == "Leukemia") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/leukemia_cancer_models/ALMANAC_klaeger_data_for_ml_leukemia.rds.gz'), compress = "gz")

prostate_cancer_data = this_dataset %>% 
  filter(PANEL == "Prostate Cancer") %>% 
  write_rds(here('results/ALMANAC_klaeger_models/prostate_cancer_models/ALMANAC_klaeger_data_for_ml_prostate.rds.gz'), compress = "gz")
```

```{r}
#cell line eda
lung_cell_lines = lung_cancer_data %>% 
  group_by(CELLNAME) %>% 
  summarise(n = n())

breast_cell_lines = breast_cancer_data %>% 
  group_by(CELLNAME) %>% 
  summarise(n = n()) %>% 
  mutate(subtype = case_when(
    CELLNAME == "BT-549" ~ "TNBC B",
    CELLNAME == "MDA-MB-231/ATCC" ~ "TNBC B",
    CELLNAME == "MDA-MB-468" ~ "TNBC A",
    CELLNAME == "HS 578T" ~ "TNBC B",
    CELLNAME == "MCF7" ~ "Luminal A",
    CELLNAME == "T-47D" ~ "Luminal A",
    TRUE ~ CELLNAME
  ))
```

```{r}
#cell sensitivity eda for breast cancer
set.seed(2222)

#randomly select x% of all combos for visualization 

all_combos = breast_cancer_data %>% 
  select(drug1, drug2) %>% 
  unique() %>% 
  mutate(combo = paste0(drug1, " + ", drug2)) %>% 
  slice_sample(prop = 0.5)

visualization_data = breast_cancer_data %>% 
  select(-starts_with(c("act_", "exp_"))) %>% 
  left_join(breast_cell_lines %>% 
              select(CELLNAME, subtype)) %>%
  mutate(combo = paste0(drug1, " + ", drug2)) %>%
  filter(combo %in% all_combos$combo) %>% 
  group_by(subtype, combo, CONC1, CONC2) %>% 
  summarise(viability = mean(viability)) %>% 
  #mutate(combo = paste0(drug1, " + ", drug2, " in ", subtype)) %>% 
  drop_na()

visualization_data_summary = visualization_data %>% 
  group_by(subtype, combo) %>% 
  summarise(mean_viability = mean(viability)) %>% 
  arrange(subtype, mean_viability)

visualization_data_processed = visualization_data %>% 
  ungroup() %>% 
  mutate(combo = fct_relevel(combo,  c("Sorafenib + Pazopanib", "Gefitinib + Axitinib", "Vemurafenib + Gefitinib", "Lapatinib + Gefitinib", "Lapatinib + Crizotinib", "Imatinib + Axitinib", "Dasatinib + Axitinib", "Vandetanib + Pazopanib", "Lapatinib + Axitinib", "Erlotinib + Crizotinib", "Ruxolitinib + Crizotinib", "Vemurafenib + Vandetanib", "Crizotinib + Axitinib", "Ruxolitinib + Axitinib", "Vemurafenib + Crizotinib","Sunitinib + Ruxolitinib", "Sunitinib + Axitinib", "Lapatinib + Imatinib", "Sunitinib + Pazopanib", "Ruxolitinib + Pazopanib", "Nilotinib + Axitinib",  "Sunitinib + Dasatinib", "Sunitinib + Nilotinib", "Sorafenib + Nilotinib", "Nilotinib + Imatinib", "Sorafenib + Imatinib"))) 

summary_combos = visualization_data_summary %>% 
  ungroup() %>% 
  select(combo) %>% 
  unique() %>% 
  anti_join(visualization_data %>% ungroup %>% select(combo) %>% unique())


visualization_data_processed %>% 
  #slice_sample(prop = 0.25) %>% 
  #filter(subtype == "TNBC A") %>% 
  #mutate(combo = paste0(drug1, " + ", drug2)) %>%
	ggplot(aes(x = viability, y = combo, fill = subtype)) +
	 stat_density_ridges(
    geom = "density_ridges_gradient", calc_ecdf = TRUE
  ) +
  scale_fill_viridis_d() +
	theme_ridges(center_axis_labels = TRUE) + 
	labs(title = " ",x = "Cell Viability", y = "Kinase Inhibitor Combinations", fill = "Subtype") +
	coord_cartesian(clip = "off") +
  theme(
    #axis.text.y = element_blank(),
    #axis.text.y = element_text(angle = 45, vjust = 1, hjust = 1),
    legend.position = "bottom",
    legend.direction = "horizontal",
    #legend.position = "blank",
    text = element_text(size = 11)
  ) 
ggsave(here('figures/ALMANAC_klaeger/cell_viability_EDA.png'), height = 15, width = 15, units = "cm")

  

visualization_data_processed %>% 
	ggplot(aes(x = viability, y = combo, colour = subtype)) +
  geom_jitter() +
	labs(title = " ",x = "Cell Viability", y = "Kinase Inhibitor Combinations", colour = "Breast Cancer Subtype") +
	coord_cartesian(clip = "off") +
  facet_wrap(~subtype) +
  theme(
    axis.text.y = element_blank(),
    legend.position = "bottom",
    legend.direction = "horizontal",
    text = element_text(size = 11)
  ) 
ggsave(here('figures/ALMANAC_klaeger/cell_viability_EDA_alternate.png'), height = 15, width = 15, units = "cm")
```
