---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(tidymodels)
library(tictoc)
library(doParallel)
library(patchwork)
library(ggupset)
```


```{r}

#data = vroom(here('results/PRISM_LINCS_klaeger_all_multiomic_data_for_ml.csv'))
all_cor = read_csv(here('results/PRISM_LINCS_klaeger_all_multiomic_data_feature_correlations.csv'))

```


# Assess Full Data Correlations

```{r}

per_group_rank = all_cor %>%
	group_by(feature_type) %>%
	nest() %>%
	mutate(group_rank = map(data, ~ .x %>% 
														mutate(sub_percent_rank = percent_rank(abs_cor*-1),
																	 sub_rank = 1:n()))) %>%
	unnest(cols = c(group_rank)) %>%
	ungroup() %>%
	select(feature,sub_rank,sub_percent_rank) %>%
	identity()

all_cor = all_cor %>%
	left_join(per_group_rank)
```

## Overall Feature Correlation Plotting

### Full Correlation Histograms
```{r}
ggplot(all_cor, aes(x=abs_cor)) +
	geom_histogram() +
	BerginskiRMisc::theme_berginski() +
	labs(x="Absolute Value Correlation", y="Number of Features") +
	xlim(c(0,NA)) +
	facet_wrap(~feature_type,scales = "free_y")

ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/feature_cor_histograms.png'),width=6,height=3)
BerginskiRMisc::trimImage(here('figures/feature_selection_all/feature_cor_histograms.png'))

ggplot(all_cor, aes(x=abs_cor, y=after_stat(density), color=feature_type)) +
	geom_freqpoly() +
	BerginskiRMisc::theme_berginski() +
	labs(x="Absolute Value Correlation", y="Density of Features", color="")

ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/feature_cor_freqpoly.png'),width=6,height=3)
```

### By Feature Type - Percentile Rank
```{r}
per_rank = ggplot(all_cor, aes(x=rank,y=sub_percent_rank,color=feature_type)) +
	geom_line(size=1.5, alpha=0.75) +
	labs(x="Overall Correlation Rank",y="Percentile Rank within Feature", color='') +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_perc_rank.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_perc_rank.png'))

per_rank_zoom = ggplot(all_cor %>% filter(rank <= 5500), aes(x=rank,y=sub_percent_rank,color=feature_type)) +
	geom_line(size=1.5, alpha=0.75) +
	labs(x="Overall Correlation Rank",y="Percentile Rank within Feature", color='') +
	scale_x_continuous(breaks=seq(0,4000,by=2000)) +
	theme(legend.position = "none", aspect.ratio = 1:1) +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_perc_rank_zoom.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_perc_rank_zoom.png'))
```

### By Feature Type - Overall Rank
```{r}
rank_full = ggplot(all_cor, aes(x=rank,y=sub_rank,color=feature_type)) +
	geom_line(size=1.5, alpha=0.75) +
	labs(x="Overall Correlation Rank",y="Number of Features", color='') +
	theme(plot.margin = margin(0, 0.5, 0, 0, "cm")) +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_rank_count.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_rank_count.png'))

ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/selection_order_full.png'), 
			 plot = rank_full + 
			 	per_rank +
			 	plot_layout(guides = "collect") &
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=7.5,height=3.2)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/selection_order_full.png'))


rank_zoom = ggplot(all_cor %>% filter(rank <= 5500), aes(x=rank,y=sub_rank,color=feature_type)) +
	geom_line(size=1.5, alpha=0.75) +
	labs(x="Overall Correlation Rank",y="Number of Features", color='') +
	scale_x_continuous(breaks=seq(0,4000,by=2000)) +
	theme(legend.position = "none", aspect.ratio = 1:1) +
	BerginskiRMisc::theme_berginski()
ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_rank_count_zoom.png'),width=6*0.75,height=5*0.75)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/group_rank_count_zoom.png'))

ggsave(here('figures/PRISM_LINCS_klaeger/feature_selection_all/selection_order.png'), 
			 plot = rank_zoom + 
			 	per_rank_zoom + 
			 	plot_layout(guides = "collect") & 
			 	theme(legend.position = 'bottom', legend.margin=margin(0,0,0,0), legend.box.margin=margin(-10,-10,-10,-10)),
			 width=7,height=3.2)
BerginskiRMisc::trimImage(here('figures/PRISM_LINCS_klaeger/feature_selection_all/selection_order.png'))
```

