---
title: "Find LINCS-PRISM Drug Matches"
author: "Matthew Berginski"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(BerginskiRMisc)
library(tidyverse)
library(here)
library(readxl)

```

```{r}
#READING IN DATA
LINCS_UNC_KINOMEscan = read_csv(here('results/full_LINCS_UNC_1uM_data_imputed.csv'))

PRISM = read_csv(here('data/PRISM/secondary/secondary-screen-replicate-treatment-info.csv'))
```

```{r}
#DATA PROCESSING

#count NAs
LINCS_UNC_KINOMEscan %>% filter(is.na(Percent.Control)) %>% count(Small.Molecule.Name)
```

```{r}
#CREATING MATCH SETS
LINCS_compound_match_set = LINCS_UNC_KINOMEscan %>%
  select(Small.Molecule.Name) %>%
	mutate(Small.Molecule.Name = trimws(Small.Molecule.Name)) %>%
  rename('name' = Small.Molecule.Name) %>%
	mutate(lower_case_name = tolower(name)) %>%
	mutate(no_dash_name = str_replace(name,"-","")) %>% 
	unique() %>%
	filter(!is.na(name))

PRISM_match_set = PRISM %>%
	select(broad_id, name) %>%
	mutate(name = trimws(name)) %>%
	unique() %>%
	filter(!is.na(name))

matches = LINCS_compound_match_set %>% 
	left_join(PRISM_match_set, by = "name") %>%
	rename(reg_broad_id = broad_id) %>%
	left_join(PRISM_match_set, by = c('lower_case_name'='name')) %>%
	rename(lower_broad_id = broad_id) %>%
	left_join(PRISM_match_set, by = c('no_dash_name'='name')) %>%
	rename(no_dash_broad_id = broad_id) %>%
	mutate(broad_id = case_when(
		!is.na(reg_broad_id) ~ reg_broad_id,
		!is.na(lower_broad_id) ~ lower_broad_id,
		!is.na(no_dash_broad_id) ~ no_dash_broad_id,
		TRUE ~ "No Match"
	)) %>%
	filter(broad_id != "No Match") %>% 
	rename('LINCS_name' = name) %>% 
	left_join(PRISM_match_set, by = 'broad_id') %>% 
	rename('PRISM_name' = name) %>% 
	unique() %>% 
	identity()

LINCS_no_matches = LINCS_compound_match_set %>%
	filter(!name %in% c(matches$name, matches$lower_case_name, matches$no_dash_name))

PRISM_no_matches = PRISM_match_set %>%
	filter(!broad_id %in% matches$broad_id)

write_csv(LINCS_no_matches, here('src/data_organization/find_LINCS_PRISM_matches/no_clear_match_LINCS_drug_list_percent.csv'))
write_csv(PRISM_no_matches, here('src/data_organization/find_LINCS_PRISM_matches/no_clear_match_PRISM_drug_list_percent.csv'))
```

From here we opened each individual drug list file and manually matched the drug names, producing "manual_matches.csv". 

```{r}
manual_matches = read_csv(here('src/data_organization/find_LINCS_PRISM_matches/manual_matches_percent.csv'))

manual_matches_filtered = manual_matches %>%
	left_join(PRISM_match_set, by = c('PRISM_name'='name')) %>% 
	filter(LINCS_name %in% LINCS_compound_match_set$name)

combined_match_list = matches %>%
	mutate(manual_match_broad_id = NA) %>%
	# select(drug,broad_id) %>%
	bind_rows(manual_matches_filtered %>%
							rename('manual_PRISM_name' = PRISM_name) %>% 
							rename(manual_match_broad_id = broad_id)) %>%
	mutate(broad_id = ifelse(is.na(broad_id), manual_match_broad_id, broad_id)) %>% 
	select(everything(),manual_match_broad_id,broad_id) %>% 
	mutate(PRISM_name = if_else(
		is.na(PRISM_name),
					manual_PRISM_name,
					PRISM_name)
	)
	
	write_csv(combined_match_list, here('results/LINCS_PRISM_match_list_percent_updated.csv'))

unmatched_LINCS = LINCS_compound_match_set %>% 
		filter(!name %in% combined_match_list$name)
		
unmatched_PRISM = PRISM_match_set %>%
	filter(! broad_id %in% combined_match_list$broad_id)

write_csv(unmatched_LINCS,here('src/data_organization/find_LINCS_PRISM_matches/unmatched_LINCS_percent.csv'))
write_csv(unmatched_PRISM,here('src/data_organization/find_LINCS_PRISM_matches/unmatched_PRISM_percent.csv'))
```