---
title: "Find ALMANAC-Klaeger Drug Matches"
author: "Chinmaya Joisa"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(webchem)
library(conflicted)
conflict_prefer("filter", "dplyr")
```

```{r}
#READING IN DATA
klaeger_cids = read_csv(here('results/matching/klaeger_cids.csv')) %>% 
	mutate(cid = as.character(cid))

validation_data = read_csv(here('results/ALMANAC_klaeger_models/breast_cancer_models/validation/all_validation_data.csv'))
```

```{r}
#DATA PROCESSING
validation_matchlist = validation_data %>% 
	rename("validation_name" = drug2) %>% 
  select(validation_name) %>% 
  unique() %>% 
  bind_rows(validation_data %>% 
	rename("validation_name" = drug1) %>% 
  select(validation_name) %>% 
  unique())
```

```{r}
#CREATING MATCH SETS
validation_cid = get_cid(unique(validation_matchlist$validation_name), from = "name", domain = "compound", match = "all", verbose = T) 

validation_full_cids = validation_cid %>% 
	rename(validation_name = query) %>% 
	left_join(validation_matchlist) %>% 
	filter(!is.na(cid)) %>% 
  filter(!is.na(validation_name)) %>% 
	write_csv(here('results/matching/validation_all_cids.csv'))
	
matches = klaeger_cids %>% 
	left_join(validation_full_cids, by = 'cid') %>% 
	filter(!is.na(validation_name))

klaeger_no_matches = klaeger_cids %>%
	filter(!cid %in% matches$cid)

validation_no_matches = validation_full_cids %>%
	filter(!cid %in% matches$cid)
```

```{r}
#including manual matches
manual_matches = data.frame(
	klaeger_name = c("MK-2206", "MK-2206", "MK-2206", "Sunitinib","Sunitinib", "Sorafenib", "Sorafenib", "LY-2584702", "LY-2584702", "Erlotinib", "Imatinib", "Imatinib"),
	validation_name = c("MK-2206 2HCl", "MK-2206-2HCl", "MK2206", "Sunitinib Malate", "Sunitinib-Malate", "Sorafenib Tosylate", "Sorafenib-Tosylate", "LY2584702 Tosylate","LY2584702-Tosylate", "Erlotinib HCl", "Imatinib Mesylate", "Imatinib-Mesylate")
) %>% 
	left_join(klaeger_cids) %>% 
	left_join(validation_matchlist)

full_matches = manual_matches %>% 
	bind_rows(matches)

klaeger_no_matches = klaeger_cids %>%
	filter(!cid %in% full_matches$cid)

validation_no_matches = validation_full_cids %>%
	filter(!cid %in% full_matches$cid)
```


```{r}
#Write Output Files
write_csv(full_matches, here('results/matching/validation_klaeger_matches.csv'))
```

