```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
#read in data

##Tim's data: Lapatinib synergy screen in SKBR3
tim_validation_data = read_csv(here('data/Synergy_data_collection/usable_data/lapatinib_synergy_screen_readable_SKBR3.csv')) %>% 
  filter(Class == "Kinase") %>% 
  separate(Compound, into = c('drug2', "synonym"), sep = " \\(") %>% 
  select(-synonym, -Targets, -Class) %>% 
  rename(CONC1 = lapatinib_conc) %>% 
  pivot_longer(`10`:`10000`, names_to = "CONC2", values_to = "viability") %>% 
  mutate(drug1 = "Lapatinib",
         CONC1 = case_when(
           CONC1 == "4.1nM" ~ 4.1*10^(-9),
           CONC1 == "12.8nM" ~ 12.8*10^(-9),
           CONC1 == "37nM" ~ 111*10^(-9),
           CONC1 == "333nM" ~ 333*10^(-9),
           CONC1 == "1uM" ~ 1*10^(-6),
           TRUE ~ 0
         ),
         CONC2 = as.numeric(CONC2)*10^(-9),
         cell_line = "SKBR3"
         )

##Sam's data: Trametinib synergy screen in SUM149, MDAMB231, HCC1806, WHIM12

#loop through all individual files

sam_file_key = data.frame(
  file_name = c("149plus_trametinib.csv", "231_trametinib.csv", "1806_trametinib.csv", "W12_trametinib.csv"),
  cell_line = c("SUM149pos", "MDAMB231", "HCC1806", "WHIM12")) %>%
  mutate(file_path = here('data/Synergy_data_collection/usable_data/sam_usable', file_name))
  
sam_validation_data = data.frame()

for (i in 1:4) {

this_cell_line_data = data.frame()
this_column_data = data.frame()

#data had 16 drugs each for 11 columns, each separated by 9
  for (column_number in c(2, 11, 20, 29, 38, 47, 56, 65, 74, 83, 92)) {
    
    for (row_number in c(1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91, 100, 109, 118, 127, 136)) { 
    
    this_file_path = sam_file_key$file_path[i]
    this_cell_line = sam_file_key$cell_line[i]
    anchor_drug = "Trametinib"
    
    this_file = read_csv(this_file_path, col_names = FALSE)
    
    col_start = column_number
    col_end = column_number+7
    row_start = row_number
    row_end = row_number+7
    
    this_drug_data_raw = this_file %>% 
      select(col_start:col_end) %>% 
      slice(row_start:row_end)
    
    this_drug_data = this_drug_data_raw %>%
      row_to_names(row_number = 1) %>% 
      mutate(drug1 = anchor_drug, drug2 = this_drug_data_raw %>% slice(1) %>% pull(1)) %>% 
      rename(CONC1 = 1) %>% 
      pivot_longer(`0`:`10000`, names_to = "CONC2", values_to = "viability_inverse") %>%
      #viability values are represented as 0 = no cell death and 1 = full death. We need the inverse.
      mutate(viability = 1-viability_inverse) %>% 
      select(-viability_inverse) %>% 
      mutate(cell_line = this_cell_line)
    
    this_column_data = bind_rows(this_column_data, this_drug_data)
    } 
  this_cell_line_data = bind_rows(this_cell_line_data, this_column_data)  
  }
sam_validation_data = bind_rows(sam_validation_data, this_cell_line_data)
}

write_csv(sam_validation_data, here('data/Synergy_data_collection/usable_data/sam_data_complied.csv'))

## Denis Data: Trametinib synergy screen in SUM159

#loop through 4 drug files
denis_drugs = c("Dinaciclib", "Erlotinib", "MK2206", "Palbociclib")

denis_validation_data = data.frame()

for (this_drug in denis_drugs) {

this_drug_path = here('data/Synergy_data_collection/usable_data/trametinib_library_synergy_denis_SUM159', paste0(this_drug, '.txt'))  

this_drug_data = read_tsv(this_drug_path) %>% 
  rename(CONC2 = 1) %>% 
  mutate(drug2 = this_drug) %>% 
  pivot_longer(-c(drug2, CONC2), names_to = "drug_conc", values_to = "value") %>% 
  mutate(
    drug1 = case_when(
      str_detect(drug_conc, regex("Tram", ignore_case = TRUE)) ~ "Trametinib",
      TRUE ~ "DMSO"
    )
  ) %>% 
  separate(drug_conc, into = c("CONC1", "other"), sep = " ") %>% 
  mutate(CONC2 = 10^(CONC2),
         CONC1 = case_when(
      CONC1 == "1000nM" ~ 1000*10^(-9),
      CONC1 == "300nM" ~ 300*10^(-9),
      CONC1 == "100nM" ~ 100*10^(-9),
      CONC1 == "30nM" ~ 30*10^(-9),
      CONC1 == "10nM" ~ 10*10^(-9),
      CONC1 == "1nM" ~ 1*10^(-9),
      CONC1 == "100pM" ~ 0.1*10^(-9),
      TRUE ~ 0)
  ) %>% 
  select(-other) %>% 
  rename(viability = value)

denis_validation_data = bind_rows(denis_validation_data, this_drug_data)

}

```

```{r}
#read in cell line info

cell_info = read_csv(here('data/CCLE_data/sample_info.csv')) %>% 
  select(DepMap_ID, stripped_cell_line_name, primary_disease, lineage_sub_subtype, lineage_molecular_subtype)

#processing and summarising replicates

all_validation_data = sam_validation_data %>%
  drop_na() %>% 
  #changing all concentration units to M
  mutate(CONC1 = as.numeric(CONC1)*10^(-9),
         CONC2 = as.numeric(CONC2)*10^(-9),
         cell_line = if_else(
           cell_line == "SUM149pos",
           "SUM149PT",
           cell_line
         )) %>% 
  mutate(origin = "Sam") %>% 
  bind_rows(tim_validation_data %>% 
              mutate(viability = viability/100,
                     origin = "Tim")
            ) %>% 
  bind_rows(denis_validation_data %>% 
              mutate(cell_line = "SUM159PT",
                     viability = viability/100,
                     origin = "Denis")
            ) %>% 
  select(drug1, drug2, CONC1, CONC2, cell_line, viability) %>% 
  group_by(drug1, drug2, CONC1, CONC2, cell_line) %>% 
  summarise(viability = mean(viability))
```

